#!/bin/bash

if [ -r /usr/share/java-utils/java-functions ]; then
  . /usr/share/java-utils/java-functions
else
  echo "Can't read Java functions library, aborting"
  exit 1
fi

ODCS="/usr/lib/odcs/backend/target/backend-1.0.0.jar"
ODCS_CFG="/usr/lib/odcs/config.properties"
ODCS_PID="/var/run/odcs_backend.pid"
set_javacmd
echo $ODCS_PID


if [ "$1" = "start" ]; then
     nohup ${JAVACMD} $JAVA_OPTS -jar "$ODCS"  -c $ODCS_CFG & 
     pid="$!"
    if [ ! -z "$ODCS_PID" ]; then
       echo "$pid" > $ODCS_PID
    fi
    echo $pid > $ODCS_PID
    exit 0
elif [ "$1" = "start-security" ]; then
  ${JAVACMD} $JAVA_OPTS  \
    -jar "$ODCS" 

    if [ ! -z "$ODCS_PID" ]; then
      echo $! > $ODCS_PID
    fi
elif [ "$1" = "stop" ]; then
   for KILLPID in `ps ax | grep 'backend-1.0.0.jar -c '$ODCS_CFG | grep -v 'grep' | awk ' { print $1;}'`; do 
   kill -15 $KILLPID;
done
    
else
  echo "Usage: $0 {start|start-security|stop}"
  exit 1
fi
